name: aifoundry-agentsv2-demo
metadata:
  template: aifoundry-agentsv2-demo
infra:
  provider: bicep
  path: infra
services:
  teamsbingagent:
    project: ./agents/50-pb-teams-bing-agent
    host: containerapp
    language: python
    docker:
      path: Dockerfile
      context: .
      image: pb-teams-bing-agent
hooks:
  preprovision:
    shell: sh
    run: sh ./scripts/set-user-principal-id.sh
